import '../styles/global.css';
import { Providers } from '../components/Providers/Providers';
import { AuthTemplate } from '../components/Auth/components/Auth.Template';
import { DM_Sans } from 'next/font/google';

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata = {
  title: 'Devscale Indonesia',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <Providers>
          <AuthTemplate>{children}</AuthTemplate>
        </Providers>
      </body>
    </html>
  );
}
