import '../styles/global.css';
import { Providers } from '../components/Providers/Providers';
export const metadata = {
  title: 'Welcome to platform',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
